name: Unit Tests

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.18

      - name: Compile Code
        run:
          make all

      - name : Run Unit Tests
        run:
          make run_tests

      - name: Clean up workspace
        run:
          make clean
